/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package GUI;

/**
 *
 * @author Lenovo
 */
import Object.KaryawanDAO;
import Object.Karyawan;
import Object.KaryawanService;
import Object.Kehadiran;
import Object.KehadiranDAO;
import com.mongodb.client.MongoDatabase;
import org.bson.Document;
import Object.MongoManager;
import javax.swing.*;
import java.awt.*;
import java.util.List;

public class AdminPage extends javax.swing.JPanel {

    /**
     * Creates new form AdminPage
     */
    public AdminPage() {
        initComponents();
        btnAbsensi = new JButton("Absensi");
        btnAbsensi.addActionListener(e -> {
            JFrame frame = (JFrame) SwingUtilities.getWindowAncestor(this);
            frame.setContentPane(new AdminAbsensiPage()); // ganti ke halaman AdminAbsensiPage
            frame.revalidate();
            frame.repaint();
        });

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        BtnAddUser = new javax.swing.JButton();
        btnAbsensi = new javax.swing.JButton();
        btnRefresh = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        btnCariNama = new javax.swing.JTextField();
        btnCari = new javax.swing.JButton();
        jPanelKaryawan = new javax.swing.JPanel();

        jPanel1.setBackground(new java.awt.Color(255, 153, 153));

        jPanel2.setBackground(new java.awt.Color(0, 51, 153));

        jButton1.setText("LOGOUT");
        jButton1.addActionListener(this::jButton1ActionPerformed);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("User Management");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(19, 19, 19))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jLabel1))
                .addGap(17, 17, 17))
        );

        jPanel4.setBackground(new java.awt.Color(0, 51, 153));

        BtnAddUser.setText("Tambah User");
        BtnAddUser.addActionListener(this::BtnAddUserActionPerformed);

        btnAbsensi.setText("Absensi");
        btnAbsensi.addActionListener(this::btnAbsensiActionPerformed);

        btnRefresh.setText("REFRESH");
        btnRefresh.addActionListener(this::btnRefreshActionPerformed);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(BtnAddUser)
                .addGap(18, 18, 18)
                .addComponent(btnAbsensi)
                .addGap(18, 18, 18)
                .addComponent(btnRefresh)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnAddUser)
                    .addComponent(btnAbsensi)
                    .addComponent(btnRefresh))
                .addContainerGap(8, Short.MAX_VALUE))
        );

        jPanel5.setBackground(new java.awt.Color(0, 255, 255));

        jLabel4.setText("Nama : ");

        btnCariNama.addActionListener(this::btnCariNamaActionPerformed);

        btnCari.setText("CARI");
        btnCari.addActionListener(this::btnCariActionPerformed);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCariNama, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnCari)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(btnCariNama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCari))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(112, 112, 112)
                        .addComponent(jLabel2)
                        .addGap(0, 864, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jPanel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap())))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelKaryawan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelKaryawan, javax.swing.GroupLayout.PREFERRED_SIZE, 550, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        // Ambil frame induk dari AdminPage (karena AdminPage adalah JPanel)
        javax.swing.JFrame parentFrame
                = (javax.swing.JFrame) javax.swing.SwingUtilities.getWindowAncestor(this);

        // Tutup frame Admin
        parentFrame.dispose();

        // Buka kembali halaman Login
        javax.swing.JFrame loginFrame = new javax.swing.JFrame("Login");
        loginFrame.setDefaultCloseOperation(javax.swing.JFrame.EXIT_ON_CLOSE);
        loginFrame.setContentPane(new LoginPage()); // LoginPage juga JPanel
        loginFrame.pack();
        loginFrame.setLocationRelativeTo(null);
        loginFrame.setVisible(true);


    }//GEN-LAST:event_jButton1ActionPerformed

    private void BtnAddUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnAddUserActionPerformed

        JFrame parentFrame = (JFrame) SwingUtilities.getWindowAncestor(this);
        UserFormDialog dialog = new UserFormDialog(parentFrame);
        dialog.setVisible(true);

        if (dialog.isSaved()) {
            KaryawanDAO dao = new KaryawanDAO(MongoManager.getDatabase());
            Karyawan k = new Karyawan(
                    dialog.getUidRfid(),
                    dialog.getId(),
                    dialog.getNama(),
                    dialog.getRole(),
                    dialog.getUsername(),
                    dialog.getPassword()
            );
            dao.save(k);
            JOptionPane.showMessageDialog(this, "User berhasil ditambahkan!");
            btnRefreshActionPerformed(evt);
        }
    }//GEN-LAST:event_BtnAddUserActionPerformed

    private void btnRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshActionPerformed

        KaryawanService service = new KaryawanService();
        service.tampilkanSemuaKaryawan(jPanelKaryawan);


    }//GEN-LAST:event_btnRefreshActionPerformed

    private void btnAbsensiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAbsensiActionPerformed

        // Buat instance halaman AdminAbsensiPage
        AdminAbsensiPage absensiPage = new AdminAbsensiPage();

        // Ambil frame utama tempat AdminPage ditampilkan
        JFrame frame = (JFrame) SwingUtilities.getWindowAncestor(this);

        // Ganti konten frame dengan halaman AdminAbsensiPage
        frame.setContentPane(absensiPage);
        frame.revalidate();
        frame.repaint();


    }//GEN-LAST:event_btnAbsensiActionPerformed

    private void btnCariNamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCariNamaActionPerformed

        String keyword = btnCariNama.getText().trim(); // pastikan ini JTextField
        jPanelKaryawan.removeAll(); // nama panel sesuai di desain

        if (keyword.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Masukkan nama atau ID terlebih dahulu!");
            return;
        }

        KaryawanDAO dao = new KaryawanDAO(MongoManager.getDatabase());
        List<Karyawan> hasil = dao.findByKeyword(keyword);

        if (hasil.isEmpty()) {
            JLabel lblKosong = new JLabel("Data tidak ditemukan.");
            lblKosong.setFont(new Font("Arial", Font.BOLD, 14));
            lblKosong.setForeground(Color.RED);
            jPanelKaryawan.add(lblKosong);
        } else {
            for (Karyawan k : hasil) {
                JPanel card = new JPanel();
                card.setLayout(new GridLayout(0, 1));
                card.setBackground(new Color(255, 204, 153));
                card.setBorder(BorderFactory.createLineBorder(Color.GRAY, 1));
                card.setPreferredSize(new Dimension(200, 120));

                card.add(new JLabel("Nama: " + k.getNamaLengkap()));
                card.add(new JLabel("Role: " + k.getRole()));
                card.add(new JLabel("Username: " + k.getUsername()));
                card.add(new JLabel("Password: " + k.getPassword()));

                jPanelKaryawan.add(card);
            }
        }

        jPanelKaryawan.revalidate();
        jPanelKaryawan.repaint();


    }//GEN-LAST:event_btnCariNamaActionPerformed

    private void btnCariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCariActionPerformed
        jPanelKaryawan.setLayout(new FlowLayout(FlowLayout.LEFT, 15, 15));

        String keyword = btnCariNama.getText().trim();
        jPanelKaryawan.removeAll();

        if (keyword.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Masukkan nama atau ID terlebih dahulu!");
            return;
        }

        KaryawanDAO dao = new KaryawanDAO(MongoManager.getDatabase());
        List<Karyawan> hasil = dao.findByKeyword(keyword);

        if (hasil.isEmpty()) {
            JLabel lblKosong = new JLabel("Data tidak ditemukan.");
            lblKosong.setFont(new Font("Arial", Font.BOLD, 14));
            lblKosong.setForeground(Color.RED);
            jPanelKaryawan.add(lblKosong);
        } else {
            for (Karyawan k : hasil) {
                JPanel card = new JPanel();
                card.setLayout(new BorderLayout());
                card.setBackground(new Color(255, 204, 153));
                card.setBorder(BorderFactory.createLineBorder(Color.GRAY, 1));
                card.setPreferredSize(new Dimension(280, 130));

                // Bagian info karyawan
                JPanel infoPanel = new JPanel(new GridLayout(0, 1));
                infoPanel.setOpaque(false);
                infoPanel.add(new JLabel("Nama: " + k.getNamaLengkap()));
                infoPanel.add(new JLabel("Role: " + k.getRole()));
                infoPanel.add(new JLabel("Username: " + k.getUsername()));
                infoPanel.add(new JLabel("Password: " + k.getPassword()));
                card.add(infoPanel, BorderLayout.CENTER);

                // Bagian tombol CRUD
                JButton btnDetail = new JButton("Detail");
                JButton btnUpdate = new JButton("Update");
                JButton btnDelete = new JButton("Delete");

                JPanel btnPanel = new JPanel(new FlowLayout(FlowLayout.CENTER));
                btnPanel.setOpaque(false);
                btnPanel.add(btnDetail);
                btnPanel.add(btnUpdate);
                btnPanel.add(btnDelete);
                card.add(btnPanel, BorderLayout.SOUTH);

                // 🔹 Aksi tombol Detail
                btnDetail.addActionListener(e -> {
                    JOptionPane.showMessageDialog(this,
                            "Detail Karyawan:\nNama: " + k.getNamaLengkap()
                            + "\nRole: " + k.getRole()
                            + "\nUsername: " + k.getUsername()
                            + "\nPassword: " + k.getPassword());
                });

                // 🔹 Aksi tombol Update (username, password, role)
                btnUpdate.addActionListener(e -> {
                    String newUsername = JOptionPane.showInputDialog(this,
                            "Masukkan username baru:", k.getUsername());
                    String newPassword = JOptionPane.showInputDialog(this,
                            "Masukkan password baru:", k.getPassword());
                    String newRole = JOptionPane.showInputDialog(this,
                            "Masukkan role baru:", k.getRole());

                    if (newUsername != null && newPassword != null && newRole != null) {
                        k.setUsername(newUsername);
                        k.setPassword(newPassword);
                        k.setRole(newRole);
                        dao.update(new Document("idKaryawan", k.getIdKaryawan()), k);
                        JOptionPane.showMessageDialog(this, "Data berhasil diperbarui!");
                        btnRefreshActionPerformed(evt);
                    }
                });

                // 🔹 Aksi tombol Delete
                btnDelete.addActionListener(e -> {
                    int confirm = JOptionPane.showConfirmDialog(this,
                            "Hapus " + k.getNamaLengkap() + "?", "Konfirmasi", JOptionPane.YES_NO_OPTION);
                    if (confirm == JOptionPane.YES_OPTION) {
                        dao.delete(new Document("idKaryawan", k.getIdKaryawan()));
                        JOptionPane.showMessageDialog(this, "Data berhasil dihapus!");
                        btnRefreshActionPerformed(evt);
                    }
                });

                jPanelKaryawan.add(card);
            }

        }

        jPanelKaryawan.revalidate();
        jPanelKaryawan.repaint();

    }//GEN-LAST:event_btnCariActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnAddUser;
    private javax.swing.JButton btnAbsensi;
    private javax.swing.JButton btnCari;
    private javax.swing.JTextField btnCariNama;
    private javax.swing.JButton btnRefresh;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanelKaryawan;
    // End of variables declaration//GEN-END:variables
}
