/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package GUI;

/**
 *
 * @author Lenovo
 */
import Object.KaryawanDAO;
import Object.Karyawan;
import service.KaryawanService;
import Object.Kehadiran;
import Object.KehadiranDAO;
import com.mongodb.client.MongoDatabase;
import org.bson.Document;
import Object.MongoManager;
import javax.swing.*;
import java.awt.*;
import java.util.List;
import utility.LanguageComboBox;
import utility.LanguageManager;

public class AdminPage extends javax.swing.JPanel {

    /**
     * Creates new form AdminPage
     */
    public AdminPage() {
        initComponents();
        btnRefreshActionPerformed(null);
        reloadTexts();


    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        btnLogout = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        BtnCariNama = new javax.swing.JTextField();
        BtnCari = new javax.swing.JButton();
        jPanelKaryawan = new javax.swing.JPanel();
        jPanel22 = new javax.swing.JPanel();
        BtnAddUser = new javax.swing.JButton();
        btnAbsensi = new javax.swing.JButton();
        btnRefresh = new javax.swing.JButton();
        Absen = new javax.swing.JButton();

        jPanel1.setBackground(new java.awt.Color(255, 153, 153));

        jPanel2.setBackground(new java.awt.Color(0, 51, 153));

        btnLogout.setText("LOGOUT");
        btnLogout.addActionListener(this::btnLogoutActionPerformed);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("User Management");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnLogout)
                .addGap(19, 19, 19))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnLogout)
                    .addComponent(jLabel1))
                .addGap(79, 79, 79))
        );

        jPanel5.setBackground(new java.awt.Color(0, 255, 255));

        jLabel4.setText("Nama : ");

        BtnCariNama.addActionListener(this::BtnCariNamaActionPerformed);

        BtnCari.setText("CARI");
        BtnCari.addActionListener(this::BtnCariActionPerformed);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BtnCariNama, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(BtnCari)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(BtnCariNama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtnCari))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(118, 118, 118)
                .addComponent(jLabel2)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2))
        );

        jPanel22.setBackground(new java.awt.Color(0, 51, 153));

        BtnAddUser.setText("Tambah User");
        BtnAddUser.addActionListener(this::BtnAddUserActionPerformed);

        btnAbsensi.setText("Riwayat Absensi");
        btnAbsensi.addActionListener(this::btnAbsensiActionPerformed);

        btnRefresh.setText("REFRESH");
        btnRefresh.addActionListener(this::btnRefreshActionPerformed);

        Absen.setText("Absen");
        Absen.addActionListener(this::AbsenActionPerformed);

        javax.swing.GroupLayout jPanel22Layout = new javax.swing.GroupLayout(jPanel22);
        jPanel22.setLayout(jPanel22Layout);
        jPanel22Layout.setHorizontalGroup(
            jPanel22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel22Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(BtnAddUser)
                .addGap(18, 18, 18)
                .addComponent(btnAbsensi)
                .addGap(18, 18, 18)
                .addComponent(Absen)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 655, Short.MAX_VALUE)
                .addComponent(btnRefresh)
                .addContainerGap())
        );
        jPanel22Layout.setVerticalGroup(
            jPanel22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel22Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnAddUser)
                    .addComponent(btnAbsensi)
                    .addComponent(btnRefresh)
                    .addComponent(Absen))
                .addContainerGap(10, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel22, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelKaryawan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel22, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanelKaryawan, javax.swing.GroupLayout.PREFERRED_SIZE, 454, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(127, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(36, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
    
    private void reloadTexts() {
        jLabel1.setText(LanguageManager.get("admin.userManagement"));
        btnLogout.setText(LanguageManager.get("button.logout"));
        BtnAddUser.setText(LanguageManager.get("admin.addUser"));
        btnAbsensi.setText(LanguageManager.get("admin.absensiHistory"));
        Absen.setText(LanguageManager.get("admin.absen"));
        btnRefresh.setText(LanguageManager.get("button.refresh"));
        jLabel4.setText(LanguageManager.get("admin.searchName"));
        BtnCari.setText(LanguageManager.get("button.search"));
}
    
    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed

        // Ambil frame induk dari AdminPage (karena AdminPage adalah JPanel)
        javax.swing.JFrame parentFrame
                = (javax.swing.JFrame) javax.swing.SwingUtilities.getWindowAncestor(this);

        // Tutup frame Admin
        parentFrame.dispose();

        // Buka kembali halaman Login
        javax.swing.JFrame loginFrame = new javax.swing.JFrame("Login");
        loginFrame.setDefaultCloseOperation(javax.swing.JFrame.EXIT_ON_CLOSE);
        loginFrame.setContentPane(new LoginPage()); // LoginPage juga JPanel
        loginFrame.pack();
        loginFrame.setLocationRelativeTo(null);
        loginFrame.setVisible(true);


    }//GEN-LAST:event_btnLogoutActionPerformed

    private void BtnAddUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnAddUserActionPerformed

        JFrame parentFrame = (JFrame) SwingUtilities.getWindowAncestor(this);
        UserFormDialog dialog = new UserFormDialog(parentFrame);
        dialog.setVisible(true);

        if (dialog.isSaved()) {
            KaryawanDAO dao = new KaryawanDAO(MongoManager.getDatabase());
            Karyawan k = new Karyawan(
                    dialog.getUidRfid(),
                    dialog.getId(),
                    dialog.getNama(),
                    dialog.getRole(),
                    dialog.getUsername(),
                    dialog.getPassword()
            );
            dao.save(k);
            JOptionPane.showMessageDialog(this, "User berhasil ditambahkan!");
            btnRefreshActionPerformed(evt);
        }
    }//GEN-LAST:event_BtnAddUserActionPerformed

    private void btnRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshActionPerformed

        KaryawanService service = new KaryawanService();
        service.tampilkanSemuaKaryawan(jPanelKaryawan);


    }//GEN-LAST:event_btnRefreshActionPerformed

    private void btnAbsensiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAbsensiActionPerformed

        // Buat instance halaman AdminAbsensiPage
        AdminAbsensiPage absensiPage = new AdminAbsensiPage();

        // Ambil frame utama tempat AdminPage ditampilkan
        JFrame frame = (JFrame) SwingUtilities.getWindowAncestor(this);

        // Ganti konten frame dengan halaman AdminAbsensiPage
        frame.setContentPane(absensiPage);
        frame.revalidate();
        frame.repaint();


    }//GEN-LAST:event_btnAbsensiActionPerformed

    private void BtnCariNamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCariNamaActionPerformed

        String keyword = BtnCariNama.getText().trim(); // pastikan ini JTextField
        jPanelKaryawan.removeAll(); // nama panel sesuai di desain

        if (keyword.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Masukkan nama atau ID terlebih dahulu!");
            return;
        }

        KaryawanDAO dao = new KaryawanDAO(MongoManager.getDatabase());
        List<Karyawan> hasil = dao.findByKeyword(keyword);

        if (hasil.isEmpty()) {
            JLabel lblKosong = new JLabel("Data tidak ditemukan.");
            lblKosong.setFont(new Font("Arial", Font.BOLD, 14));
            lblKosong.setForeground(Color.RED);
            jPanelKaryawan.add(lblKosong);
        } else {
            for (Karyawan k : hasil) {
                JPanel card = new JPanel();
                card.setLayout(new GridLayout(0, 1));
                card.setBackground(new Color(255, 204, 153));
                card.setBorder(BorderFactory.createLineBorder(Color.GRAY, 1));
                card.setPreferredSize(new Dimension(200, 120));

                card.add(new JLabel("Nama: " + k.getNamaLengkap()));
                card.add(new JLabel("Role: " + k.getRole()));
                card.add(new JLabel("Username: " + k.getUsername()));
                String masked = k.getPassword().replaceAll(".", "*");
                card.add(new JLabel("Password: " + masked));

                jPanelKaryawan.add(card);
            }
        }

        jPanelKaryawan.revalidate();
        jPanelKaryawan.repaint();


    }//GEN-LAST:event_BtnCariNamaActionPerformed

    private void BtnCariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCariActionPerformed

    String keyword = BtnCariNama.getText().trim();

    if (keyword.isEmpty()) {
        JOptionPane.showMessageDialog(this,
                "Masukkan nama atau ID terlebih dahulu!");
        return;
    }

    KaryawanService service = new KaryawanService();
    service.tampilkanHasilPencarian(jPanelKaryawan, keyword);


    }//GEN-LAST:event_BtnCariActionPerformed

    private void AbsenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AbsenActionPerformed
                                     
    // Buat instance halaman AttendancePage, kirim AdminPage sebagai halaman asal
    AttendancePage attendancePage = new AttendancePage(this);
    // Ambil frame utama tempat panel ini ditampilkan
    javax.swing.JFrame frame = (javax.swing.JFrame) javax.swing.SwingUtilities.getWindowAncestor(this);
    // Ganti konten frame dengan halaman AttendancePage
    frame.setContentPane(attendancePage);
    frame.revalidate();
    frame.repaint();

    }//GEN-LAST:event_AbsenActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Absen;
    private javax.swing.JButton BtnAddUser;
    private javax.swing.JButton BtnCari;
    private javax.swing.JTextField BtnCariNama;
    private javax.swing.JButton btnAbsensi;
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnRefresh;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel22;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanelKaryawan;
    // End of variables declaration//GEN-END:variables
}
